### ISSUE TITLE
!Undefined control sequence

### ISSUE THREAD

**Issue by EzraYyy** [zcysxy/obsidian-pandoc-filters#2]
After deleting the two lines including "template:" and "${USERDATA}/filters/preamble.lua" in yaml.pdf,the following shell command still cannot be run. The error prompt is: Undefined control sequence as shown in the attachment where "D:\ software" is the installation root directory of the texlive2017.
![!Undefined control sequence](https://github.com/zcysxy/obsidian-pandoc-filters/assets/150313349/5bec886a-e7ef-4ff8-a73a-6e0bb522c295)

**Comment by zcysxy** [comment]
Can you paste the content of `pandoc-filter-test.md` here? Also, can you execute pandoc without the defaults file to see if the issue persists? That is, execute `pandoc -o output.pdf pandoc-filter-test.md`.

**Comment by EzraYyy** [comment]
When I Executed pandoc without the defaults file,the pdf file was generated successfully ([pandoc-flter-test.pdf](https://github.com/zcysxy/obsidian-pandoc-filters/files/13303933/pandoc-flter-test.pdf)).The content of `pandoc-filter-test.md` as follws.

---
title: Obsidian Pandoc
author: Ezra
uni: Obsidian University # this is a variable specified in templates/scribe.tex
---

## pandoc test
pandoc --defaults E:/Ezra_Local_Ob/Toil/ZJYP/pandoc-filters-main/defaults/pdf.yaml E:/Ezra_Local_Ob/Toil/ZJYP/Pandoc-test/pandoc-flter-test.md

pandoc --defaults E:/Ezra_Ob_Files/ZJYP/pandoc-filters-main/defaults/pdf.yaml E:/Ezra_Ob_Files/ZJYP/Pandoc-test/pandoc-flter-test.md

pandoc -o pandoc-flter-test.pdf E:/Ezra_Ob_Files/ZJYP/Pandoc-test/pandoc-flter-test.md

[pandoc latex ! Undefined control sequence. - clovershell](https://www.cnblogs.com/clovershell/p/14653611.html)

[yaml ${}](https://blog.csdn.net/jackback17566/article/details/118547660)

[Pandoc - Pandoc User’s Guide](https://pandoc.org/MANUAL.html#defaults-files)

**Comment by EzraYyy** [comment]
The above issue was solved by enabling the choose of system called "Provide global language support using Unicode UTF-8".However, there is another warning:"Could not fetch resource test-1.png: replacing image with description" 
![could not fetch resource](https://github.com/zcysxy/obsidian-pandoc-filters/assets/150313349/263fa1dd-1ddc-4ad6-9abd-9519b81c9717)

**Comment by zcysxy** [comment]
Can you elaborate on how to "Provide global language support using Unicode UTF-8"? The new issue says that pandoc cannot find the image in the note. Maybe the path is incorrect. For example, you can omit the folder name of an image in Obsidian, but this does not work with pandoc. And excalidraw is currently not supported.

**Comment by EzraYyy** [comment]
The directory of  "Provide global language support using Unicode UTF-8" in windows 10 is Control Panel/Clock and Region/Region/Management. I just wonder how to modify the image.lua file to achieve the function of omitting the absolute path of the image in md file by specifying the folder path where the image is located in image.lua.

**Comment by zcysxy** [comment]
> I just wonder how to modify the image.lua file to achieve the function of omitting the absolute path of the image in md file by specifying the folder path where the image is located in image.lua.

That's a good idea! I will close this issue and open another one (https://github.com/zcysxy/obsidian-pandoc-filters/issues/3) to track this feature request.

**Comment by EzraYyy** [comment]
Thank you so much!Looking forward to good news.

> > I just wonder how to modify the image.lua file to achieve the function of omitting the absolute path of the image in md file by specifying the folder path where the image is located in image.lua.
> 
> That's a good idea! I will close this issue and open another one (#3) to track this feature request.
