### ISSUE TITLE
obsidian的高亮语法==被高亮的内容==会报错

### ISSUE THREAD

**Issue by calmwaves111** [zcysxy/obsidian-pandoc-filters#4]
感谢您提供的配置，目前发现一个问题，如果md文档里有==高亮==语法，就会报错，不知道是pandoc的原因还是tex的原因
看报错似乎是由于被识别成h1标题，但我对此也不太懂

![image](https://github.com/zcysxy/obsidian-pandoc-filters/assets/56907077/c5cb9a44-15a9-4290-aca9-ad7cdd29bd80)

md原文长这样
```text
所以在工作中拆解目标时，很容易陷入“困难”、“复杂”的问题中去，而实际上，==识别那些问题更重要==，哪怕它是简单枯燥的，那也应该优先解决它们。
```

**Comment by zcysxy** [comment]
我加了一个处理高亮的 filter, 你看下还有问题不

**Comment by calmwaves111** [comment]
还是这个报错，加粗没事，高亮有问题

![image](https://github.com/zcysxy/obsidian-pandoc-filters/assets/56907077/f5e7bf7a-1caa-4284-b14f-14a560e4476b)

问题不大，我以后用加粗就行

**Comment by zcysxy** [comment]
哦哦这是一个新的关于中文的问题，更新一下 `filters/preamble.lua` 应该就可以修复了

**Comment by calmwaves111** [comment]
好啦高亮正常啦，谢谢大佬的耐心
