### ISSUE TITLE
Undefined references.

### ISSUE THREAD

**Issue by Shash-Sen** [zcysxy/obsidian-pandoc-filters#6]
Hi, I am a complete noob so this might actually have a quick fix.
I am trying to convert a test file to pdf using the filters and the tools. But I keep getting undefined references error. I have uploaded the shell output file, md and yaml.
[PandocTest.txt](https://github.com/user-attachments/files/16328507/PandocTest.txt)
[Testlatex.md](https://github.com/user-attachments/files/16328509/Testlatex.md)
[pdfyaml.txt](https://github.com/user-attachments/files/16328518/pdfyaml.txt)

**Comment by zcysxy** [comment]
Hi, undefined references are just warnings. The error is

```console
! You can't use `macro parameter character #' in horizontal mode.
<argument> ##
             Section
l.154 written in \hyperref[section-1]{#Section}
```

That is, your headings should not contain the character `#`, which is a preserved character for Markdown headings.

**Comment by Shash-Sen** [comment]
Hi, thank you for the quick reply. That comes to the second problem. The obsidian links do not seem to be converted to latex type referencing. I don't know if the Lua filter should do that. I am getting ?? in the pdf format. 
[output2.pdf](https://github.com/user-attachments/files/16330187/output2.pdf)

**Comment by zcysxy** [comment]
Hi, this is something to do with your TeX syntax. To reference an equation in LaTeX, the equation needs a label and a tag. As Mathjax, which Obsidian uses to render math, does not support labels, you need to escape the `\label` command (see below). Additionally, the block-id should match the label. The following example should work.

```tex
Hi this is a test file with no equations or figures or bib.
$$
%\label{ca32dc}
\tag{1}
a \equiv b
$$

^ca32dc

The purpose of this section is to call the equation [[#^ca32dc]] 
```

**Comment by Shash-Sen** [comment]
Perfect. It worked.
